# Generated by Django 2.2.1 on 2019-05-07 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='用户头像')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户token')),
                ('token_expire', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='token过期时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'users',
            },
        ),
    ]
