# Generated by Django 2.2.1 on 2019-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='GroupId')),
                ('chat_id', models.IntegerField(blank=True, null=True, verbose_name='ChatId')),
                ('group_name', models.CharField(blank=True, default='聊天室', max_length=255, null=True, verbose_name='聊天室名称')),
            ],
            options={
                'verbose_name': '群聊信息',
                'verbose_name_plural': '群聊信息',
                'db_table': 'group',
            },
        ),
    ]
