# Generated by Django 2.2.1 on 2019-06-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190609_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ChatId'),
        ),
    ]
